### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by bengalspice** [dyaters68/intro-data-capstone-biodiversity#1]
**Code**
- Since this was done in the Learning Environment, there was no code to review. 

**Slides**
- There is a lot of white space. This is very harsh on the eyes. Try choosing a slide theme to make your presentation more visually appealing.
- The slides don't state why you created this presentation. What is the story behind the tables and graphs? Considering the hard work you put into coding for data analysis, you should have included a slide for each of the following:
-- A title slide
-- A section describing the data in species_info.csv. Be sure to include some (or all) of **what you noticed** while working through the notebook.
-- A section describing the significance calculations that you did for endangered status between different categories of species.
-- A recommendation for conservationists concerned about endangered species, based on your significance calculations
-- A section describing the sample size determination that you did for the foot and mouth disease study
-- All of the graphs that you created in the notebook
- If you run Chi-Square tests, you should have included the exact pvalues in the slides to determine significance.
- The slides also feel very out of order. 

### **I suggest redoing your slide deck and uploading a new one. I'll be happy to look over revisions.**

**Comment by dyaters68** [comment]
[Capstone Presentation.pdf](https://github.com/dyaters68/intro-data-capstone-biodiversity/files/2219507/Capstone.Presentation.pdf)

**Comment by dyaters68** [comment]
Here is another attempy

**Comment by bengalspice** [comment]
Much better! Looks Great!
